# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d8057d2c2a5efd6a8e82b25cb13023aabb85739fd42b81bedaab4ddf8594ce6dc38e458e402379b0175e430ad858d4a91785ee93614298eca820db770c03f2

test:
  secret_key_base: 70b75dbf44cc74ad9ca4f8aef7f656f0c6a578f94e031a11fd3f1a8e6bf5d5e29aed6ca4b8bdaf99a8827abad27de16a16bcf4b3fd77523b343be621910fb29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
